security:
#  user:
#    password: password
#  oauth2:
#    client:
#      client-id: demo
#      client-secret: demo
#      scope: read, write
#      auto-approve-scopes: .*
#    authorization:
#      check-token-access: permitAll()
server:
  host: 127.0.0.1
  port: 9999
  #context-path: /uaa
  session:
    cookie:
      name: AUTHORIZATION_SESSION
logging:
  level:
    org.springframework.security: DEBUG