#auth-server: http://localhost:9999/uaa
auth-server: http://localhost:9999
server:
  host: 127.0.0.1
  port: 8081
  session:
    cookie:
      name: UI2_SESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: ui2
      client-secret: ui2-secret
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
      scope: read, write
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
logging:
  level:
    org.springframework.security: DEBUG
spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat


